apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169958654
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169958654
    app.kubernetes.io/part-of: test-app-169958654
  name: java-quarkus-169958654
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169958654
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169958654
    spec:
      containers:
      - image: quay.io/hacdev/sm2yecdw-tenant/test-app-169958654/java-quarkus-169958654@sha256:c005d39c0472feefe18f927fd96b4e7d100bef7b4b7b105128fd9905c2096329
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
