apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169958654
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/sm2yecdw-tenant/test-app-169958654/java-quarkus-169958654@sha256:c005d39c0472feefe18f927fd96b4e7d100bef7b4b7b105128fd9905c2096329
        name: my-java-quarkus
        resources: {}
status: {}
